export {default as Navbar} from './Navbar'
export {default as Footer} from './Footer'
export {default as Layout} from './Layout'
export {default as Hero} from './Hero'
export {default as Categories} from './Categories'
export {default as Incentives } from './Incentives'
export {default as Trending} from './Trending'
export {default as Cta} from './CTA'
export {default as ProductPage} from './ProductPage'
export {default as RelatedProducts} from './RelatedProducts'
export {default as BasicModal} from './BasicModal'
export {default as RegisterForm} from './RegisterForm'
export {default as LoginForm} from './LoginForm'
export {default as Loader} from './Loader'